### ISSUE TITLE
Cleanup of working directory on windows fails with access denied

### ISSUE THREAD

**Issue by tomzo** [gocd-contrib/gocd-golang-agent#29]
## Steps to reproduce

This happens on most recent agents published on [bintray](https://bintray.com/gocd-contrib/gocd_golang_goagent/download_file?file_path=goagent%2F1.1%2Fgocd-golang-agent_windows_amd64_1.1.exe)

Create a pipeline and select to clean working directory in stage configuration.

With just one agent, build will fail on second execution with error like this:

```
17:49:32.982 Deleting folder C:\GoLangAgent\2\pipelines\windows-sample\.git
17:49:33.138 ERROR: remove C:\GoLangAgent\2\pipelines\windows-sample\.git\objects\pack\pack-8cc5d3e0b439b369c7e7448468aba3c2c7361556.idx: Access is denied.
```
## Possible solution

I can reproduce this consistently. I guess that agent has an open handle on something inside git repo when it starts to delete the repository. I'll try finding this in code.

**Comment by barrowkwan** [comment]
This is the problem with older version of Golang where the os.RemoveAll cannot remove file or directory with READ-ONLY flag set on Windows (https://github.com/golang/go/issues/9606) Golang v1.7.3 has the fixed merged.  I have released new version 1.5 of golang goagent which compile with golang v1.7.3 and should have this issue fixed.
