### ISSUE TITLE
artifact md5sum missing on windows fetch

### ISSUE THREAD

**Issue by tomzo** [gocd-contrib/gocd-golang-agent#31]
Fetching artifact fails on windows agent. Might be related to #30 

golang agent running on windows, trying to fetch artifact from previous stage. Artifact was built by golang agent on windows. 
## Build log

```
01:51:16.871 [go] Fetching artifact [build/bin] from [libstc-windows.ci/3322cfc6/build/latest/debug]
01:51:18.183 ERROR: [WARN] The md5checksum value of the artifact [build/bin/Debug\libstc_test.exe] was not found on the server. Hence, Go could not verify the integrity of its contents.
```

**Comment by barrowkwan** [comment]
This is different than the one that I saw #30.  I will take a look at that

**Comment by tomzo** [comment]
here is repo to reproduce https://github.com/tomzo/golang-artifacts-bug31
