### ISSUE TITLE
Support generateTestReport command: from nunit test report

### ISSUE THREAD

**Issue by xli** [gocd-contrib/gocd-golang-agent#8]
similar with #3, support parse nunit test report.

**Comment by ayatsynych** [comment]
+1

**Comment by yunlzheng** [comment]
@xil I notice there have two release version of nunit: 2.x and 3.x. The report xml schema is different. Should we support both of the them?

http://nunit.org/files/testresult_25.txt
http://nunit.org/files/testresult_30.txt

**Comment by xli** [comment]
@yunlzheng yes, we should be able to parse out any kind of nunit test report. But feel free to start with supporting one format.
